# Generated by Django 5.0.6 on 2024-08-29 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_address_phone_delete_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='created_by',
        ),
    ]
