# Generated by Django 5.0.6 on 2024-08-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_address_created_by_remove_phone_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30)),
                ('description', models.CharField(default='', max_length=30)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
