# Generated by Django 5.0.6 on 2024-08-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_counter_delete_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trustedclient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trusted')),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
