# Generated by Django 5.0.6 on 2024-08-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustedclient',
            name='company',
            field=models.CharField(default='', max_length=40),
        ),
    ]
