# Generated by Django 5.0.6 on 2024-08-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_trustedclient_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trustedclient',
            name='company',
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.CharField(default='', max_length=40),
        ),
    ]
