# Generated by Django 5.0.6 on 2024-08-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_trustedclient_company_project_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
